### ISSUE TITLE
Get STARRY working on everyone's computers

### ISSUE THREAD

**Issue by meganmansfield** [multidworlds/eigenspectra#45]

**Comment by jlustigy** [comment]
I have no problem running `starry` on my personal computer and have verified that our code that uses `starry` works on other computers. It would be helpful for each of you who still have issues running the code to try the following steps:

1. [Install starry](https://rodluger.github.io/starry/install.html) (preferably using conda-forge):
`conda config --add channels conda-forge`
`conda install starry`
2. Generate hot spot eclipse light curves using starry:
```python
# From the eigenspectra top-most directory:

# Import the code used to generate the eclipse lightcurves
from gen_lightcurves import *

# Get the high-res wavelength grid and pixel spectra (spaxels)
lamhr, spaxels = prep_spectral_hotspot_map()

# Generate the multi-wavelength eclipse lightcurves using starry
time, lam, dlam, lcurves = create_lightcurves_with_starry(lamhr, spaxels, plot_lightcurves = False, plot_diagnostic = False)
```
And that should do it! 

**Please respond to this thread if you experience problems running this test.** 

If you run the above code with `plot_lightcurves = True`, you should get the following plot:

<img width="1087" alt="lcs" src="https://user-images.githubusercontent.com/8882466/53458076-813e0780-39e9-11e9-8d6a-b9cffe485c71.png">

And if you use `plot_diagnostic = True`: 

<img width="1049" alt="fpfs" src="https://user-images.githubusercontent.com/8882466/53458094-99158b80-39e9-11e9-9108-3e5d82214d49.png">

**Comment by meganmansfield** [comment]
I just tried this and it works fine on my computer now! Thanks for the fix!

**Comment by jlustigy** [comment]
Woot! Glad to hear it 👍

**Comment by rodluger** [comment]
🎉🎉🎉🎉
